import { AuthProvider } from "./Providers";
import { CartContextProvider } from "@/contexts/CartContext";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartContextProvider>
            <div>
              <div id="modal"></div>
              {children}
            </div>
          </CartContextProvider>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
